WIP on issue #89
CenterForDigitalHumanities/glossing-entries pull request #108
Opened 2023-10-29 01:48 UTC by KamBustos

I am working on a bug of duplicate glosses appearing for this sprint. There are some Glosses that appear more than once. They are the exact same gloss -- same title and same @id. They should only appear once. You can view this bug at this link: https://glossing.rerum.io/glosses.html?gog-filter=JTdCJTIydGl0bGUlMjIlM0ElMjJOb24lMjB0ZXJyZWFudCUyMHJ1aW5lJTIyJTJDJTIydGV4dCUyMiUzQSUyMk5vbiUyMHRlcnJlYW50JTIwcnVpbmUlMjIlMkMlMjJ0YXJnZXRlZHRleHQlMjIlM0ElMjJOb24lMjB0ZXJyZWFudCUyMHJ1aW5lJTIyJTdE

Bug:
![issue_89](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/108566070/e210e46d-c924-4591-abc0-81933c1c4ced)

I am currently working in the files of glosses.html and ng.js. The DockerFile is for testing and will be removed when finalized PR is requested for review.

2023-11-03 19:24 UTC, thehabes requested changes
I ran into an error when partially through this review.  The comments are applicable still, you have some changes to make and clean up to do.

http://localhost:8080/gloss-transcription.html?tpen-project=https://t-pen.org/TPEN/project/7084 does not load due to an error from the template.  Please investigate.

2023-11-03 19:24 UTC, thehabes commented on glosses.html
> +        function removeDuplicateDeerIds() {
You do not need any of the code on this page.  As am I testing locally, I deleted all of this and it functions just fine.  Delete this from the PR.

2023-11-03 19:24 UTC, thehabes commented on js/ng.js
> +    // Only care about witness form
Not sure what go you here.  None of this code should be edited.  Remove all of these changes from the PR.

2023-11-03 19:24 UTC, thehabes commented on js/deer-config.js
> +            const deduplicatedList = removeDuplicates(obj[options.list], '@id')
You should be doing this inside `if(options.list)`.  If there is no `options.list` here, which is possible, you will get a null pointer exception.

2023-11-03 19:24 UTC, thehabes commented on js/deer-config.js
> +                );
No semicolon.

2023-11-03 19:24 UTC, thehabes commented on js/deer-config.js
> +            const total = deduplicatedList.length
If `total` is dependent upon `deduplicatedList`, you will have to set it inside of `if(options.list)` as well.

2023-11-06 17:55 UTC, AbhilashKotha approved these changes

2023-11-06 19:18 UTC, thehabes approved these changes

2023-11-06 19:31 UTC, AbhilashKotha approved these changes

2023-11-06 19:32 UTC, merged