WIP on #68 - custom confirm modal
CenterForDigitalHumanities/glossing-entries pull request #131
Opened 2023-11-13 19:31 UTC by cohen-j

Started design of the custom confirm modal. As I have only implemented the visual part of the modal (see below), it cannot be tested yet. The next thing I need to do for this issue is create functionality so it can be used in place of the browser's native `confirm()`.
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/123422590/ab2787ec-a7b5-45be-ab02-f3ebec9624dd)

2023-11-30 06:26 UTC, cohen-j commented
a custom confirm modal (see below) should be implemented in all previous places where native browser confirm was used.

see `confirmModal.js` for the modal itself and `shared.js` for the helper function. other file changes pertain to either adding `<confirm-modal>` to html or changing `confirm()` to `modalConfirm()`

![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/123422590/52376722-15bd-4de2-ba3d-2fcdd9486c40)

2023-12-02 02:21 UTC, AbhilashKotha commented on js/confirmModal.js
> +                    <h2 id="confirm-message"></h2>
I don't think it is correct to use an h2 for a message. can you change it to a <p> with a bigger font size?

2023-12-07 19:40 UTC, thehabes requested changes
Tested on 
http://localhost:8080/ng.html#https://devstore.rerum.io/v1/id/6507cd02ee7021a5f6a454cf

I got the dialog
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/d0a2bb3b-036b-4177-a5e4-0f282586d581)

However, when I clicked 'OK', the delete did not happen.

Tested on http://localhost:8080/gloss-transcription.html#https://devstore.rerum.io/v1/id/65259f9ba2ad2e20e5172530

I got the dialog
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/29443c54-199a-4153-911d-a23e5f6775ea)

However, when I clicked 'OK', the delete did not happen.

I do not believe this is functioning as expected.

2023-12-11 15:58 UTC, cubap requested changes
see @thehabes issue

2024-03-04 01:49 UTC, KamBustos commented
For Sprint 3 I am picking up this issue that Josh was working on. So far, I have merged changes from the main, and I plan to refine and add to Josh's preexisting work for the remained of Sprint 3.

2024-08-08 20:54 UTC, closed without merging