WIP #184
CenterForDigitalHumanities/glossing-entries pull request #185
Opened 2024-02-26 01:25 UTC by xXCrash2BomberXx

2024-02-26 18:49 UTC, thehabes requested changes
Some immediate thingsI noticed...

First, you are allowed to come into the page with a search query.  When I do, the area does not make sense.

glosses.html?gog-filter=JTdCJTIydGl0bGUlMjIlM0ElMjJjb25jZXJuJTIyJTJDJTIydGV4dCUyMiUzQSUyMmNvbmNlcm4lMjIlMkMlMjJ0YXJnZXRlZHRleHQlMjIlM0ElMjJjb25jZXJuJTIyJTdE
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/3aadc8b9-b67e-4643-a234-21622859da94)

Second, there are no instructions for what "New Gloss" does.  Add some instructions.
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/f120e953-d2f4-4e09-a437-3e8ae38fc03f)

Third, when I click "New Gloss", it submits an empty, untitled Gloss.  That button should not actually create an entity, especially since there are no instructions telling you what you should expect to have happen.  You should use some kind of confirm modal to have the user confirm they want to make a Gloss with the title they typed.

Fourth, you have resurrected a bug.  When I use the "Enter" button on my keyboard while my cursor is in the filter it submits the form and creates the Gloss.  "Enter" should not cause that form to submit and right now does not at https://glossing.rerum.io

Take your time and be a little more careful here.  This should stay in Draft until you have done more testing.

2024-03-06 23:30 UTC, thehabes requested changes
Much better, it worked nicely this time.  There a couple of small things left.

The message that appears when making the new Gloss is just "Saving Successful".  I think it may have said "Gloss Saved" but the text was quickly replaced.  The message should let the user know that a Gloss was created and they are being redirected to that Gloss detail page.  Here's a screenshot.

![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/3287006/2d5ed533-b89b-4442-858c-fdac45154fc7)

Make sure not to use deer-type="named-gloss" anymore, that's the old name.  I did not realize any of those were still around.  It is ok for a form to have `id="named-gloss"` but not `deer-type="named-gloss"`.  You'll see that comment inline with the code where I noticed it.

2024-03-06 23:30 UTC, thehabes commented on js/deer-config.js
> +				<form id="ngForm" deer-type="named-gloss" deer-context="http://www.loc.gov/mods" class="row">
The value for the deer-type attribute should be "Gloss".  "named-gloss" is the old type and we have since changed it.

2024-03-14 18:32 UTC, cubap requested changes
I haven't fully tested it yet, but there are some changes to make for now or comments to respond to.

2024-03-14 18:32 UTC, cubap commented on js/deer-config.js
> +				<form id="ngForm" deer-type="Gloss" deer-context="http://www.loc.gov/mods" class="row">
I'm not certain why this is a form. There isn't a need for a creator or anything that I can see, just processing the search term. Let me know if I'm missing something.

2024-03-14 18:32 UTC, cubap commented on glosses.html
> +			addEventListener('globalFeedbackFinished', () => location.href = `ng.html#${event.detail['@id']}`)
This looks like a better way to manage it - good.

2024-03-14 18:32 UTC, cubap commented on js/deer-config.js
> +						const searchSubmit = document.getElementById('search-submit')
The whitespace looks weird here...

2024-03-14 18:32 UTC, cubap commented on js/deer-config.js
> +						const searchSubmit = document.getElementById('search-submit')
If this is just copy-paste from line 613, it shoudl be pulled out into a function and reused.

2024-03-14 18:32 UTC, cubap commented on js/deer-config.js
> +						const searchSubmit = document.getElementById('search-submit')
If this is just copy-paste from line 613, it should be pulled out into a function and reused.

2024-03-18 18:19 UTC, AbhilashKotha reviewed
Works well for me. The design is cleaner than how it was done previously.

2024-03-18 19:58 UTC, thehabes approved these changes
Works good and I like how the design ended up.  I still feel like there should be a confirm action after clicking the "can't find what you're looking for?" text because it is so freaking tempting to click it even if you aren't planning to.

2024-03-18 20:16 UTC, merged