WIP on Issue 68 Custom Confirm Modal. Refactorization
CenterForDigitalHumanities/glossing-entries pull request #197
Opened 2024-03-04 21:13 UTC by KamBustos

I am creating a separate PR because the last PR is severely outdated and I would like to add my own implementations for this. For Sprint 3 I am picking up this issue that Josh was working on. So far, I have merged changes from the main, and I plan to refine and add to Josh's preexisting work for the remainder of Sprint 3. In short, this issue entails adding a custom confirm modal, which should be implemented in all previous places where native browser confirm was used. This issue has not been worked on for a while, so there are many merge conflicts to resolve. I am working on the merge conflicts with Abhilash. This is what the latest change looks like, but when clicking "OK", the witness is not deleted:

Dialogue:
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/108566070/7220a0a2-bc27-44cc-8a6c-7f8b8d768123)

Confirmation:
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/108566070/3e581810-73bd-437b-a8ad-761158165073)

2024-03-18 18:20 UTC, AbhilashKotha reviewed
Works well for me on delete actions ( for both true and false conditions) The delete witness does not work, but it does not work on the main branch too!

2024-03-18 20:16 UTC, thehabes requested changes
I am a little worried that I see so many code changes as part of the diff that were a part of the delete refactor.  You may need to merge with `main` to get a clean diff, but I guess it's OK to move forward with it.  You will really have to keep an eye on this merge @AbhilashKotha 

This does appear to function as expected and the confirm() functionality of returning true or false is respected.

A couple of changes to make.  Since you are essentially making a custom HTML, scope your querySelectors to your HTML instead of the whole `document`.  You should be good to go after that.

I will also note that I was able to confirm() and delete a Witness.  I'll still double check on that delete after we merge.

2024-03-18 23:56 UTC, thehabes approved these changes

2024-03-19 00:21 UTC, AbhilashKotha approved these changes
lgtm

2024-03-19 00:21 UTC, merged