WIP on issue 96
CenterForDigitalHumanities/glossing-entries pull request #98
Opened 2023-10-14 23:01 UTC by KamBustos

When loading the page, specifically in the Canonical Reference Locator section, there is a bug where the user sees undefined. For example, Canonical Reference Locator: Matthew:undefined. undefined should not be appearing there. Also, see Issue https://github.com/CenterForDigitalHumanities/glossing-entries/issues/79 in relation to optimizing and cleaning code up.

Example of Bug:
![image](https://github.com/CenterForDigitalHumanities/glossing-entries/assets/108566070/7fc0c594-bd3c-43d9-9109-5a5857e655f4)

Made some changes in the code so that it checks for the primitive type of `undefined` on page load.
I edited solely the file ng.js.
Test the code by loading the page of the new gloss tab. It works correctly if `undefined` does not appear.

2023-10-22 17:12 UTC, AbhilashKotha commented
@KamBustos Great work. The bug is fixed for me. @thehabes can you take a look at this before I merge it? Thanks.

2023-10-23 17:09 UTC, thehabes requested changes

2023-10-23 17:09 UTC, thehabes commented on js/ng.js
> +                document.querySelector('[deer-key="canonicalReference"]').value = `Matthew ${event.detail.targetChapter.value || ''}${event.detail.targetVerse.value ? `:${event.detail.targetVerse.val
From testing, I no longer see any `undefined` appearances!

Looks like the right place and the right logic.  Do both the checks of `targetVerse` and `targetChapter` in the same syntax style. 

```javascript

 document.querySelector('[deer-key="canonicalReference"]').value = `Matthew ${event.detail.targetChapter.value ?  event.detail.targetChapter.value : ''}${event.detail.targetVerse.value ? `:${event.detail.targetVerse.value}` : ''}`
 
```

2023-10-23 17:12 UTC, thehabes commented on js/ng.js
> +                document.querySelector('[deer-key="canonicalReference"]').value = `Matthew ${event.detail.targetChapter.value || ''}${event.detail.targetVerse.value ? `:${event.detail.targetVerse.val
Oh nevermind!  That extra `:` you add in is why you didn't do them both like ` || ''`

2023-10-23 17:12 UTC, thehabes approved these changes

2023-10-23 17:30 UTC, AbhilashKotha approved these changes
lgtm

2023-10-23 17:32 UTC, merged